version: '2.2'
services:
  eureka-server:
    build: ./eureka
    ports:
      - "8761:8761"
    environment:
      HOST: ${HOST}
  configuration-server:
    build: ./configuration
    ports:
      - "8081:8081"
    environment:
      HOST: ${HOST}
  employees:
    build: ./employees
    ports:
      - "8080:8080"
    environment:
      HOST: ${HOST}
  zuul-getaway:
    build: ./zuul
    ports:
      - "8800:8800"
    environment:
       HOST: ${HOST}
  greeting:
    build: ./greeting
    ports:
      - "8082:8082"
    environment:
      HOST: ${HOST}
  zipkin:
    image: "openzipkin/zipkin"
    ports:
     - "9411:9411"